// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9TAKtj6F4ru65N_x-hHXs_YMjwCtljE',
    appId: '1:271728196179:web:7174a18b2d79b89a9aa4a6',
    messagingSenderId: '271728196179',
    projectId: 'proyecto-final-cdd79',
    authDomain: 'proyecto-final-cdd79.firebaseapp.com',
    storageBucket: 'proyecto-final-cdd79.firebasestorage.app',
    measurementId: 'G-XY29PMT6HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFJU29zod6xvEezKx1aiv-vshS0fvDC8',
    appId: '1:271728196179:android:32348a55a5a8d8769aa4a6',
    messagingSenderId: '271728196179',
    projectId: 'proyecto-final-cdd79',
    storageBucket: 'proyecto-final-cdd79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYl6H_TgnH3sSez7B2lHKAtceKfkEm7A0',
    appId: '1:271728196179:ios:1dbe5df793156d659aa4a6',
    messagingSenderId: '271728196179',
    projectId: 'proyecto-final-cdd79',
    storageBucket: 'proyecto-final-cdd79.firebasestorage.app',
    iosBundleId: 'com.example.tiendaRopa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYl6H_TgnH3sSez7B2lHKAtceKfkEm7A0',
    appId: '1:271728196179:ios:1dbe5df793156d659aa4a6',
    messagingSenderId: '271728196179',
    projectId: 'proyecto-final-cdd79',
    storageBucket: 'proyecto-final-cdd79.firebasestorage.app',
    iosBundleId: 'com.example.tiendaRopa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9TAKtj6F4ru65N_x-hHXs_YMjwCtljE',
    appId: '1:271728196179:web:888b8df040782fe39aa4a6',
    messagingSenderId: '271728196179',
    projectId: 'proyecto-final-cdd79',
    authDomain: 'proyecto-final-cdd79.firebaseapp.com',
    storageBucket: 'proyecto-final-cdd79.firebasestorage.app',
    measurementId: 'G-G5LN8RRXT2',
  );
}
